server:
  context-path: /data
  port: 8019
    #证书的路径.
  ssl:
      #是否开启https
      enabled: true
      key-store: classpath:keystore.p12
      #证书密码，请修改为您自己证书的密码.
      key-store-password: 475996
      #秘钥库类型(PKCS12,JKS)
      key-store-type: PKCS12
      #证书别名
      key-alias: tomcat
  
spring:
  application:
    name: data.center.service
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
    # 设置静态文件路径，js,css等
    mvc:
      static-path-pattern: /static/**
  datasource:
    switch: true
    #dao层包路径
    mapper-dao-path: com.data.dao
    #mapper-xml路径
    mapper-location-path: classpath*:mapper/*/*.xml
    ds:
      - key: master
        # 数据源类型
        #type: com.zaxxer.hikari.HikariDataSource
        type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:5306/stu_learning_system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&connectTimeout=1000&socketTimeout=3000
        username: root
        password: root

      - key: custer
        # 数据源类型
        type: com.zaxxer.hikari.HikariDataSource
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:5306/onlinemusic?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false&connectTimeout=1000&socketTimeout=3000
        username: root
        password: root

    # 初始连接数
    initial-size: 5
    # 最小连接池数量
    min-idle: 10
    # 最大连接池数量
    max-active: 20
    # 获取连接等待超时的时间
    max-wait: 60000
    # 检测间隔时间，检测需要关闭的空闲连接，单位毫秒
    time-between-eviction-runs-millis: 60000
    # 一个连接在连接池中最小的生存时间，单位毫秒
    min-evictable-idle-time-millis: 30000
    # 一个连接在连接池中最大的生存时间，单位毫秒
    max-evictable-idle-time-millis: 90000
    # 配置检测连接是否有效
    validation-query: SELECT 1 FROM DUAL
    # 如果为true(默认为false),当应用向连接池申请连接时,连接池会判断这条连接是否是可用的
    test-on-borrow: false
    # 连接返回检测
    test-on-return: false
    # 失效连接检测
    test-while-idle: true
    #poolPreparedStatements: true
    #maxOpenPreparedStatements: 20
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，缺省为所有
        allow:
        url-pattern: /druid/*
        # 登录用户名及密码
        login-username: melody
        login-password: melody
      filter:
        # 开启统计功能
        stat:
          enabled: true
          # 开启慢查询功能
          log-slow-sql: true
          slow-sql-millis: 1000
          # 合并多SQL
          merge-sql: true
        # 开启防火墙功能
        wall:
          enabled: true
          config:
            # 允许多语句同时执行
            multi-statement-allow: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+0

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        # 消息握手方式
        acknowledge-mode: manual
        # 每次队列获取消息数量
        prefetch: 250
        # 开启批量消费
        consumer-batch-enabled: true
        # 每次批量消费大小
        batch-size: 16


sync.init:
  open: false
  cron: 0/1 * * * * ?

logging:
  config: classpath:logback-spring.xml
  level:
    #日志级别
    root: info
    com.data.dao: debug
  file:
    logName: data-service-log
    max-history: 10
    max-size: 1KB

spring.main.allow-bean-definition-overriding: true

#spring.mail.host=smtp.163.com
#spring.mail.username=903936584@qq.com
#spring.mail.password=xxxxxxxxx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true



