server:
  context-path: /data
  port: 8019
  
spring:
    datasource:
        master:
            url: jdbc:mysql://127.0.0.1:3306/stu_learning_system?useUnicode=true&characterEncoding=utf8&useSSL=false
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat
            maxActive: 300
            initialSize: 5
            maxWait: 60000
            minIdle: 5
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20

        custer:
            url: jdbc:mysql://127.0.0.1:3306/onlinemusic?useUnicode=true&characterEncoding=utf8&useSSL=false
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
            filters: stat
            maxActive: 300
            initialSize: 5
            maxWait: 60000
            minIdle: 5
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest

sync.init:
  open: false
  cron: 0/1 * * * * ?

#spring.mail.host=smtp.163.com
#spring.mail.username=903936584@qq.com
#spring.mail.password=xxxxxxxxx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true



